# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Clive Jeffery
email: clive@rosedene.com
description: A blog for my technical notes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://clivemjeffery.github.io" # the base hostname & protocol for your site
twitter_username: CliveJeffery
github_username:  clivemjeffery

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

collections:
  howtos:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "howtos" # default layout for howto documents
    values:
      layout: "howto"